require('dotenv').config();
const { MongoClient } = require('mongodb');

const seedRecipes = [
  
  {
    recipeName: "Fluffy Buttermilk Pancakes",
    recipeImage: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&q=80",
    category: "breakfast",
    cuisineType: "American",
    difficultyLevel: "easy",
    preparationTime: 20,
    servings: 4,
    ingredients: ["2 cups flour", "2 eggs", "1.5 cups buttermilk", "2 tbsp butter"],
    instructions: ["Mix dry ingredients", "Whisk wet ingredients", "Combine and cook on griddle"],
    price: 0,
    isPremium: false,
    likesCount: 15,
    rating: 4.8,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Avocado Sourdough Toast",
    recipeImage: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=600&q=80",
    category: "breakfast",
    cuisineType: "American",
    difficultyLevel: "easy",
    preparationTime: 10,
    servings: 1,
    ingredients: ["1 slice sourdough", "1/2 avocado", "Red pepper flakes", "Sea salt"],
    instructions: ["Toast bread", "Mash avocado", "Spread and season"],
    price: 0,
    isPremium: false,
    likesCount: 32,
    rating: 4.9,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Acai Smoothie Bowl",
    recipeImage: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&q=80",
    category: "breakfast",
    cuisineType: "Other",
    difficultyLevel: "easy",
    preparationTime: 15,
    servings: 1,
    ingredients: ["1 frozen acai packet", "1/2 banana", "Granola", "Berries"],
    instructions: ["Blend acai and banana", "Pour into bowl", "Top with granola and berries"],
    price: 5.99,
    isPremium: true,
    likesCount: 45,
    rating: 5.0,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Margherita Pizza",
    recipeImage: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",
    category: "lunch",
    cuisineType: "Italian",
    difficultyLevel: "medium",
    preparationTime: 45,
    servings: 2,
    ingredients: ["Pizza dough", "Tomato sauce", "Fresh mozzarella", "Basil"],
    instructions: ["Roll dough", "Add sauce and cheese", "Bake at 500F for 10 mins", "Top with basil"],
    price: 0,
    isPremium: false,
    likesCount: 120,
    rating: 4.7,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Grilled Chicken Caesar Salad",
    recipeImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80",
    category: "lunch",
    cuisineType: "American",
    difficultyLevel: "easy",
    preparationTime: 25,
    servings: 2,
    ingredients: ["Romaine lettuce", "Grilled chicken breast", "Caesar dressing", "Croutons", "Parmesan"],
    instructions: ["Chop lettuce", "Slice chicken", "Toss with dressing and toppings"],
    price: 0,
    isPremium: false,
    likesCount: 88,
    rating: 4.5,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Spicy Tuna Poke Bowl",
    recipeImage: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=600&q=80",
    category: "lunch",
    cuisineType: "Japanese",
    difficultyLevel: "medium",
    preparationTime: 30,
    servings: 1,
    ingredients: ["Sushi-grade tuna", "Sushi rice", "Avocado", "Spicy mayo", "Edamame"],
    instructions: ["Cook rice", "Cube and dress tuna", "Assemble bowl with toppings"],
    price: 9.99,
    isPremium: true,
    likesCount: 205,
    rating: 4.9,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Garlic Butter Steak Bites",
    recipeImage: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&q=80",
    category: "dinner",
    cuisineType: "American",
    difficultyLevel: "medium",
    preparationTime: 20,
    servings: 2,
    ingredients: ["Sirloin steak", "Garlic", "Butter", "Parsley"],
    instructions: ["Cut steak into cubes", "Sear in hot pan", "Add butter and garlic, baste"],
    price: 0,
    isPremium: false,
    likesCount: 310,
    rating: 4.9,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Creamy Fettuccine Alfredo",
    recipeImage: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=600&q=80",
    category: "dinner",
    cuisineType: "Italian",
    difficultyLevel: "easy",
    preparationTime: 25,
    servings: 4,
    ingredients: ["Fettuccine pasta", "Heavy cream", "Parmesan cheese", "Butter", "Garlic"],
    instructions: ["Boil pasta", "Make sauce with butter, cream, garlic, and parmesan", "Toss pasta in sauce"],
    price: 0,
    isPremium: false,
    likesCount: 150,
    rating: 4.6,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Decadent Chocolate Cake",
    recipeImage: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600&q=80",
    category: "dessert",
    cuisineType: "French",
    difficultyLevel: "hard",
    preparationTime: 90,
    servings: 8,
    ingredients: ["Flour", "Cocoa powder", "Sugar", "Eggs", "Butter", "Dark chocolate"],
    instructions: ["Mix dry ingredients", "Add wet ingredients", "Bake for 35 mins", "Frost when cool"],
    price: 0,
    isPremium: false,
    likesCount: 420,
    rating: 5.0,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Strawberry Cupcakes",
    recipeImage: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&q=80",
    category: "dessert",
    cuisineType: "American",
    difficultyLevel: "medium",
    preparationTime: 45,
    servings: 12,
    ingredients: ["Flour", "Sugar", "Fresh strawberries", "Butter", "Eggs"],
    instructions: ["Puree strawberries", "Mix batter", "Bake for 20 mins", "Top with strawberry buttercream"],
    price: 0,
    isPremium: false,
    likesCount: 89,
    rating: 4.4,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Rainbow Buddha Bowl",
    recipeImage: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    category: "vegan",
    cuisineType: "Other",
    difficultyLevel: "easy",
    preparationTime: 30,
    servings: 2,
    ingredients: ["Quinoa", "Roasted chickpeas", "Sweet potato", "Kale", "Tahini dressing"],
    instructions: ["Cook quinoa", "Roast veggies and chickpeas", "Assemble and drizzle with dressing"],
    price: 0,
    isPremium: false,
    likesCount: 110,
    rating: 4.8,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Vegan Mushroom Stroganoff",
    recipeImage: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&q=80",
    category: "vegan",
    cuisineType: "Other",
    difficultyLevel: "medium",
    preparationTime: 40,
    servings: 4,
    ingredients: ["Pasta", "Cremini mushrooms", "Coconut milk", "Onion", "Garlic"],
    instructions: ["Saute mushrooms and onions", "Add coconut milk and simmer", "Toss with cooked pasta"],
    price: 4.99,
    isPremium: true,
    likesCount: 75,
    rating: 4.7,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Creamy Tomato Basil Soup",
    recipeImage: "https://images.unsplash.com/photo-1548943487-a2e4b43b4850?w=600&q=80",
    category: "vegetarian",
    cuisineType: "Italian",
    difficultyLevel: "easy",
    preparationTime: 35,
    servings: 4,
    ingredients: ["San Marzano tomatoes", "Fresh basil", "Heavy cream", "Garlic", "Vegetable broth"],
    instructions: ["Simmer tomatoes and broth", "Blend until smooth", "Stir in cream and basil"],
    price: 0,
    isPremium: false,
    likesCount: 145,
    rating: 4.9,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Mediterranean Quinoa Salad",
    recipeImage: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80",
    category: "vegetarian",
    cuisineType: "Mediterranean",
    difficultyLevel: "easy",
    preparationTime: 20,
    servings: 3,
    ingredients: ["Quinoa", "Cucumber", "Cherry tomatoes", "Feta cheese", "Olives", "Lemon vinaigrette"],
    instructions: ["Cook and cool quinoa", "Chop vegetables", "Toss everything with vinaigrette"],
    price: 0,
    isPremium: false,
    likesCount: 95,
    rating: 4.5,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Loaded Ultimate Nachos",
    recipeImage: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80",
    category: "snacks",
    cuisineType: "Mexican",
    difficultyLevel: "easy",
    preparationTime: 15,
    servings: 4,
    ingredients: ["Tortilla chips", "Cheddar cheese", "Jalapenos", "Black beans", "Sour cream"],
    instructions: ["Layer chips, beans, and cheese", "Bake until cheese melts", "Top with jalapenos and sour cream"],
    price: 0,
    isPremium: false,
    likesCount: 220,
    rating: 4.8,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Homemade Potato Chips",
    recipeImage: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=600&q=80",
    category: "snacks",
    cuisineType: "American",
    difficultyLevel: "medium",
    preparationTime: 30,
    servings: 2,
    ingredients: ["Russet potatoes", "Vegetable oil", "Sea salt"],
    instructions: ["Slice potatoes thinly", "Fry in hot oil until crispy", "Drain and salt immediately"],
    price: 0,
    isPremium: false,
    likesCount: 65,
    rating: 4.3,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Artisan Iced Latte",
    recipeImage: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80",
    category: "beverages",
    cuisineType: "Other",
    difficultyLevel: "easy",
    preparationTime: 5,
    servings: 1,
    ingredients: ["Espresso", "Milk", "Ice", "Vanilla syrup"],
    instructions: ["Brew espresso", "Pour milk over ice", "Top with espresso and syrup"],
    price: 0,
    isPremium: false,
    likesCount: 180,
    rating: 4.7,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Refreshing Summer Mojito",
    recipeImage: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&q=80",
    category: "beverages",
    cuisineType: "Other",
    difficultyLevel: "easy",
    preparationTime: 5,
    servings: 1,
    ingredients: ["White rum", "Fresh mint", "Lime", "Sugar", "Club soda", "Ice"],
    instructions: ["Muddle mint and sugar", "Add rum and lime juice", "Top with ice and club soda"],
    price: 2.99,
    isPremium: true,
    likesCount: 210,
    rating: 4.9,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Pan-Seared Salmon",
    recipeImage: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80",
    category: "seafood",
    cuisineType: "American",
    difficultyLevel: "medium",
    preparationTime: 20,
    servings: 2,
    ingredients: ["Salmon fillets", "Olive oil", "Lemon", "Garlic", "Dill"],
    instructions: ["Season salmon", "Sear skin-side down for 4 mins", "Flip and cook 3 more mins", "Serve with lemon"],
    price: 0,
    isPremium: false,
    likesCount: 155,
    rating: 4.8,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Garlic Butter Shrimp Scampi",
    recipeImage: "https://images.unsplash.com/photo-1559742811-822873691df8?w=600&q=80",
    category: "seafood",
    cuisineType: "Italian",
    difficultyLevel: "easy",
    preparationTime: 15,
    servings: 3,
    ingredients: ["Large shrimp", "Linguine", "Butter", "Garlic", "White wine", "Parsley"],
    instructions: ["Boil pasta", "Saute garlic and shrimp in butter and wine", "Toss with pasta and parsley"],
    price: 7.99,
    isPremium: true,
    likesCount: 290,
    rating: 5.0,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },

  
  {
    recipeName: "Rustic Sourdough Loaf",
    recipeImage: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    category: "bakery",
    cuisineType: "French",
    difficultyLevel: "hard",
    preparationTime: 1440,
    servings: 10,
    ingredients: ["Sourdough starter", "Bread flour", "Water", "Salt"],
    instructions: ["Mix dough and autolyse", "Bulk ferment with stretch and folds", "Shape and cold proof overnight", "Bake in Dutch oven"],
    price: 0,
    isPremium: false,
    likesCount: 400,
    rating: 4.9,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  },
  {
    recipeName: "Flaky French Croissants",
    recipeImage: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&q=80",
    category: "bakery",
    cuisineType: "French",
    difficultyLevel: "hard",
    preparationTime: 180,
    servings: 8,
    ingredients: ["Flour", "Yeast", "Milk", "Sugar", "High-quality butter for laminating"],
    instructions: ["Make dough", "Encase butter block", "Perform 3 turns/folds", "Shape, proof, and bake"],
    price: 12.99,
    isPremium: true,
    likesCount: 350,
    rating: 5.0,
    authorName: "Admin Chef",
    authorEmail: "admin@recipehub.com",
    status: "published",
    createdAt: new Date(),
  }
];

async function seed() {
  const client = new MongoClient(process.env.MONGODB_URI);
  try {
    await client.connect();
    const db = client.db();
    
    console.log("Dropping old recipes...");
    await db.collection('recipes').deleteMany({});
    
    console.log(`Inserting ${seedRecipes.length} fresh recipes...`);
    const result = await db.collection('recipes').insertMany(seedRecipes);
    
    console.log(`Successfully seeded ${result.insertedCount} recipes!`);
  } catch (err) {
    console.error("Error seeding:", err);
  } finally {
    await client.close();
  }
}

seed();
